### PR TITLE
Add option to compile with github actions

### PR DESCRIPTION
**Pull request by k3v1nwrld**
I saw the post someone made on reddit about this, and saw that many people on windows didn't know how to set up wsl2, so I thought it may be easier for them compiling with github actions. Only problem is that they need to delete the fork after they are done, cuz forks can't be privated

### CODE REVIEW

**Comment by EthanArbuckle** [comment]
thanks for looking into this. Having this action is the right direction, but right now it doesn't bring much value as a token needed to be added into the code before compiling. This is compiling a dylib with the placeholder client id

I'll leave this PR open and merge it when I find an easy way for people to supply client id

**Comment by EthanArbuckle** [comment]
Thanks for looking into this. Having this action is the right direction, but I don't want to encourage people to create public forks containing reddit API credentials (even if they are temporary).

I've been thinking of ways to make it easier to supply client_id (without needing to modify the source code). An in-app UI is an option, but users are likely generating the client_id on desktop and sending it to a device is an annoying step. Maybe the process could be DM'ing the client_id to yourself on reddit and then opening that message in Apollo. The tweak could detect this message, pull the client-id out of it and kick off the auth flow.

I'll leave this open and merge it when I land on a solution to the client id thing.

Thanks!

**Comment by andreas16700** [comment]
Another way would be to build it with docker, take the client id as an arg and use that. It'd take care of any dependencies ..but that'd require the user to install docker

**Comment by td512** [comment]
Personally I would sed the values in `Tweak.m` in the actions run. Means the client id could exist in a secret.

Something like this:

`sed -i -e 's/CLIENT_ID_GOES_HERE/${{ secrets.REDDIT_CLIENT_ID }}/g' Tweak.m` 

would work, without exposing the client id used

**Pull request closed without merging**
